#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new \ImapDump\Command\InfoCommand());
$application->add(new \ImapDump\Command\ListCommand());
$application->add(new \ImapDump\Command\DumpCommand());
$application->run();